docs: CoinJoin backup with HD
dashpay/docs pull request #132
Opened 2022-04-28 20:36 UTC by thephez

2022-04-30 02:59 UTC, strophy approved these changes

2022-04-30 19:17 UTC, UdjinM6 requested changes
Makes sense but it's not how things work atm 🙈 (HD wallet warns about low keys too)

2022-05-02 17:18 UTC, thephez commented
> Makes sense but it's not how things work atm see_no_evil (HD wallet warns about low keys too)

Does this look better?

2022-05-02 18:58 UTC, UdjinM6 approved these changes
👍

2022-05-04 12:44 UTC, merged