chore: dashmate updates
dashpay/docs pull request #218
Opened 2023-03-20 06:18 UTC by strophy

Testing has shown some edge cases in the system environment that can interfere with dashmate running. This PR documents steps users can take to avoid such issues.

2023-03-20 08:38 UTC, pshenmic commented
What if you install AppArmor on regular images where it were working correctly without it before? Could it cause any issues?

DAPI single port is only applied to v24, that is not in production (master) yet. People manages v23 networks when install dashmate by default, and its still http-grpc ports for it.

2023-03-20 16:46 UTC, pshenmic requested changes

2023-03-20 16:46 UTC, pshenmic commented on docs/user/masternodes/setup-testnet.rst
> +  DAPI:    3000
This is changed only on v24, while this doc representing the testnet the suppose to be running v23 network.

2023-03-20 16:54 UTC, thephez commented
Thanks! Formatting and stuff all looks good. I'll  just wait for resolution on the open comments.

2023-03-27 05:36 UTC, strophy commented
Pushed a change to clarify AppArmor is really optional and this step is for troubleshooting. Let's merge this once v0.24 hits testnet.

2023-03-27 14:29 UTC, thephez approved these changes
LGTM! :+1:

2023-06-13 02:16 UTC, strophy commented
Yes, let's merge

2023-06-13 13:00 UTC, thephez approved these changes

2023-06-13 13:00 UTC, merged